### ISSUE TITLE
metadata generation failed

### ISSUE THREAD

**Issue by SatchMarr** [bellingcat/auto-archiver#136]
I am having an error like this after the **pip install auto-archiver** 

_My pip version is ok, i followed all the steps in the tuto but still... Thank you very much_ 

 Using cached tiktok_downloader-0.0.7.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p4pkeoc4/tiktok-downloader_7e38f0915c9f4c168f367c7ae68d3a97/setup.py", line 9, in <module>
          long_description=open(path.join(base_dir, "README.md"), encoding="utf-8").read(),
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-p4pkeoc4/tiktok-downloader_7e38f0915c9f4c168f367c7ae68d3a97/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by SatchMarr** [comment]
I tried with pipenv but i have this error : 

pipenv run python -m src.auto_archiver --config secrets/orchestration.yaml

/home/ms/.local/share/virtualenvs/ms-zkRZG1j0/bin/python: Error while finding module specification for 'src.auto_archiver' (ModuleNotFoundError: No module named 'src')

**Comment by djhmateer** [comment]
Check you are in the correct directory eg inside this repo so probably `auto-archiver`

you should be able to see a directory called `src` when you do `ls`.

**Comment by SatchMarr** [comment]
ok thanks, it did create a virtual env but stopped at some point for a module i have in python .... wierd ... : 

✔ Successfully created virtual environment!
Virtualenv location: /home/ms/.local/share/virtualenvs/auto-archiver-noAvaoRi
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ms/Documents/auto-archiver/src/auto_archiver/__init__.py", line 1, in <module>
    from . import archivers, databases, enrichers, feeders, formatters, storages, utils, core
  File "/home/ms/Documents/auto-archiver/src/auto_archiver/archivers/__init__.py", line 1, in <module>
    from .archiver import Archiver
  File "/home/ms/Documents/auto-archiver/src/auto_archiver/archivers/archiver.py", line 5, in <module>
    import mimetypes, requests
ModuleNotFoundError: No module named 'requests'

**Comment by djhmateer** [comment]
Requests should be there: https://github.com/bellingcat/auto-archiver/blob/main/Pipfile

Try running pipenv update?
